version: '3.4'
services:
  openethereum.avado.dnp.dappnode.eth:
    image: 'openethereum.avado.dnp.dappnode.eth:10.0.7'
    build: ./build
    volumes:
      - 'data:/root/.local/share/io.parity.ethereum'
    ports:
      - '30305'
      - 30305/udp
    restart: always
    environment:
      - EXTRA_OPTS=
volumes:
  data: {}
